# Use PHP 7.3 by replacing "php72" below with "php73"
runtime: php72
# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php
handlers:
- url: /
  static_files: index.html
  upload: index.html

  - url: /css
  static_dir: css

  - url: /js
  static_dir: js

  - url: /assets
  static_dir: assets

  - url: /img
  static_dir: img

- url: /(.*)
  static_files: /\1
  upload: /(.*)